-- =============================================================================
-- shop.db → PostgreSQL (Supabase)
-- Run in: Supabase Dashboard → SQL → New query → Run
-- Or with CLI: supabase link && supabase db push
--
-- After loading data from SQLite with explicit IDs, run:
--   db/migrations/postgres/002_reset_sequences.sql
-- =============================================================================

CREATE TABLE customers (
  customer_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name         text NOT NULL,
  email             text NOT NULL UNIQUE,
  gender            text NOT NULL,
  birthdate         text NOT NULL,
  created_at        text NOT NULL,
  city              text,
  state             text,
  zip_code          text,
  customer_segment  text,
  loyalty_tier      text,
  is_active         integer NOT NULL DEFAULT 1
);

CREATE TABLE products (
  product_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku           text NOT NULL UNIQUE,
  product_name  text NOT NULL,
  category      text NOT NULL,
  price         double precision NOT NULL,
  cost          double precision NOT NULL,
  is_active     integer NOT NULL DEFAULT 1
);

CREATE TABLE orders (
  order_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     bigint NOT NULL REFERENCES customers (customer_id),
  order_datetime  text NOT NULL,
  billing_zip     text,
  shipping_zip    text,
  shipping_state  text,
  payment_method  text NOT NULL,
  device_type     text NOT NULL,
  ip_country      text NOT NULL,
  promo_used      integer NOT NULL DEFAULT 0,
  promo_code      text,
  order_subtotal  double precision NOT NULL,
  shipping_fee    double precision NOT NULL,
  tax_amount      double precision NOT NULL,
  order_total     double precision NOT NULL,
  risk_score      double precision NOT NULL,
  is_fraud        integer NOT NULL DEFAULT 0,
  fulfilled       integer NOT NULL DEFAULT 0
);

CREATE TABLE order_items (
  order_item_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       bigint NOT NULL REFERENCES orders (order_id),
  product_id     bigint NOT NULL REFERENCES products (product_id),
  quantity       integer NOT NULL,
  unit_price     double precision NOT NULL,
  line_total     double precision NOT NULL
);

CREATE TABLE shipments (
  shipment_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id          bigint NOT NULL UNIQUE REFERENCES orders (order_id),
  ship_datetime     text NOT NULL,
  carrier           text NOT NULL,
  shipping_method   text NOT NULL,
  distance_band     text NOT NULL,
  promised_days     integer NOT NULL,
  actual_days       integer NOT NULL,
  late_delivery     integer NOT NULL DEFAULT 0
);

CREATE TABLE product_reviews (
  review_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     bigint NOT NULL REFERENCES customers (customer_id),
  product_id      bigint NOT NULL REFERENCES products (product_id),
  rating          integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_datetime text NOT NULL,
  review_text     text,
  UNIQUE (customer_id, product_id)
);

CREATE TABLE order_predictions (
  order_id                    bigint PRIMARY KEY REFERENCES orders (order_id) ON DELETE CASCADE,
  late_delivery_probability   double precision NOT NULL,
  predicted_late_delivery     integer NOT NULL,
  prediction_timestamp        text NOT NULL
);

CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_datetime ON orders (order_datetime);
CREATE INDEX idx_items_order ON order_items (order_id);
CREATE INDEX idx_items_product ON order_items (product_id);
CREATE INDEX idx_shipments_late ON shipments (late_delivery);
CREATE INDEX idx_reviews_product ON product_reviews (product_id);
CREATE INDEX idx_reviews_customer ON product_reviews (customer_id);
